---
- hosts: dedicated
  gather_facts: true
  roles:
    - common
    - nginx-companion
    - lets-encrypt
    - influxdb
    - telegraf
    - logstash
    - grafana
    #- pybot
    - cuttlerat_ru
    - fastpost
    - files_hotkosc
    - hastebin
    - neobug
    - minecraft-server
    - minecraft-server-next
    - monero-miner
    - minio

- hosts: aws
  gather_facts: true
  roles:
    - common
    - pybot
    - chat-linker
