---
- name: Start minecraft-server-next container
  docker_container:
      image: java:8-jdk
      name: minecraft-server-next
      interactive: yes
      tty: yes
      working_dir: "/data"
      entrypoint: "/data/entrypoint.sh"
      restart_policy: always
      env:
          VIRTUAL_HOST: minecraft-next.hotkosc.ru
          VIRTUAL_PORT: 8124
          LETSENCRYPT_HOST: minecraft-next.hotkosc.ru
          LETSENCRYPT_EMAIL: hotkosc@gmail.com
          JAVA_TOOL_OPTIONS: -Dfml.queryResult=confirm
      volumes:
          - "/opt/data/minecraft-next:/data"
      ports:
          - "22566:25566"
      expose:
          - 8124
